export const lables = {
  comments: 'Lables are horizantly ordered',
  VolunteerName: 'שם מתנדב',
  VolunteerNumber: 'מספר מתנדב',
  IdNumber: 'תעודת זהות',
  CoordinatorName: 'רכזת',
  InstituteName: 'מוסד',
  ReportMonth: 'חודש',
  TotalWorkTime: 'סיכום שעות אפשריות בחודש',
  TotalWorkingDays: 'סיכום ימי עבודה שנשמרו',
  VolunteerWeeklyHours: 'שעות שבועיות של מתנדב',
  VolunteerWorkTime: 'סה"כ שעות למתנדב החודש',
  TotalMonthTime: 'סה”כ שעות עבודה בחודש',
  WorkTimeDiff: 'עודף שעות למתנדב',
}
export const TableLabels = {
  date: 'date',
  dayInWeek: 'dayInWeek',
  dayType: 'dayType',
  endTime: 'endTime',
  starTime: 'starTime',
  extraActivities: 'extraActivities',
  workActivity1: 'workActivity1',
  workActivityNote1: 'workActivityNote1',
  absenceType: 'absenceType',
  isSickDay: 'isSickDay',
  isSickHalfDay: 'isSickHalfDay',
  isApprovedSickDay: 'isApprovedSickDay',
  isQuarantine: 'isQuarantine',
  totalHours: 'totalHours',
  notes: 'notes',
  save: 'save',
  print: 'print',
  submitForApproval: 'submitForApproval',
}
export const fieldTypes = {
  editText: 'editText',
  checkbox: 'checkbox',
  text: 'text',
  select: 'select',
  time: 'time',
}
/*export const TableLabels = {
  date: 'תאריך',
  dayInWeek: 'יום בשבוע',
  dayType: 'שעת התחלה',
  endTime: 'שעת סיום',
  extraActivities: 'שעות פעילות אחהצ',
  workActivity1: 'פעילות',
  workActivityNote1: 'הערת פעילות',
  absenceType: 'סיבת היעדרות',
  isSickDay: 'יום מחלה',
  isSickHalfDay: 'חצי מחלה',
  isApprovedSickDay: 'מחלה מאושרת',
  isQuarantine: 'האם מחלה בידוד',
  totalHours: 'סיכום שעות',
  notes: 'הערות',
  save: 'שמור',
  print: 'הדפס',
  submitForApproval: 'הגש דוח שעות למנהל מוסד',
}
*/
